import os
from pathlib import Path
import time
from ardis.utils.autoconfig.flows import HardwareConfiguration, ParsecConfiguration, Spec2006Configuration, DefaultConfigurations


class ConfigWriter:
    DEFAULT_TEMP_DIR = "/tmp/ardis_runtime_data"

    def __init__(
        self,
        filepath: str,
        hardware_config: HardwareConfiguration,
        parsec_config: ParsecConfiguration,
        spec2006_config: Spec2006Configuration,
        default_config: DefaultConfigurations,
    ) -> None:
        self.filepath = Path(filepath)
        self.hardware_config = hardware_config
        self.parsec_config = parsec_config
        self.spec2006_config = spec2006_config
        self.default_config = default_config

    def write(self) -> None:
        """Write the configuration to the specified file."""
        try:
            config_content = self._create_config()
            self.filepath.parent.mkdir(parents=True, exist_ok=True)  # Ensure the directory exists
            self.filepath.write_text(config_content)
            print(f"Configuration file written to: {os.path.abspath(self.filepath)}")
        except Exception as e:
            raise IOError(f"Failed to write configuration file: {e}")

    def _create_config(self) -> str:
        """Generate the configuration file content."""
        sections = [
            self._write_header_section(),
            self._write_hardware_section(),
            self._write_software_section(),
            self._write_parsec_section(),
            self._write_spec2006_section(),
            self._write_default_section(),
        ]
        return "\n".join(sections)

    def _write_header_section(self) -> str:
        """Generate the header section."""
        return "\n".join([
            "# Generated by ARDIS Auto-Configuration generator",
            "# For a detailed explanation of each option, please refer to the documentation or the example configuration file.",
            f"# Machine: {Path('/proc/sys/kernel/hostname').read_text().strip()}",
            f"# Date: {time.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
        ])

    def _write_hardware_section(self) -> str:
        """Generate the hardware section."""
        return "\n".join([
            "[Hardware]",
            f"core_count = {self.hardware_config.logical_cores}",
            f"clock_domains = {self.hardware_config.frequency_domains}",
            "",
        ])

    def _write_software_section(self) -> str:
        """Generate the software section."""
        return "\n".join([
            "[Software]",
            f"temp_data_dir = {self.DEFAULT_TEMP_DIR}",
            "",
        ])

    def _write_parsec_section(self) -> str:
        """Generate the PARSEC benchmark section."""
        enabled_pkgs = self.parsec_config.enabled_packages
        disabled_pkgs = self.parsec_config.disabled_packages
        all_pkgs = sorted(enabled_pkgs.union(disabled_pkgs))

        packages = "\n".join(
            f"    {pkg}" if pkg in enabled_pkgs else f"    # {pkg}" for pkg in all_pkgs
        )

        return "\n".join([
            "[Parsec_Benchmark]",
            f"enabled = {str(self.parsec_config.enabled).lower()}",
            f"benchmark_base_dir = {self.parsec_config.parsec_base_dir}",
            "available_packages =",
            packages,
            "",
        ])

    def _write_spec2006_section(self) -> str:
        """Generate the SPEC2006 benchmark section."""
        enabled_pkgs = self.spec2006_config.enabled_packages
        disabled_pkgs = self.spec2006_config.disabled_packages
        all_pkgs = sorted(enabled_pkgs + disabled_pkgs)

        packages = "\n".join(
            f"    {pkg.split('.')[1]}" if pkg in enabled_pkgs else f"    # {pkg.split('.')[1]}" for pkg in all_pkgs
        )

        return "\n".join([
            "[Spec2006_Benchmark]",
            f"enabled = {str(self.spec2006_config.enabled).lower()}",
            f"benchmark_base_dir = {self.spec2006_config.spec_base_dir}",
            f"config_file = {self.spec2006_config.spec_config_file}",
            "available_packages =",
            packages,
            "",
        ])

    def _write_default_section(self) -> str:
        """Generate the default experiment section."""
        periodic_app_events = "\n".join(f"    {event}" for event in self.default_config.periodic_app_level_events)
        periodic_system_events = "\n".join(f"    {event}" for event in self.default_config.periodic_system_wide_events)
        one_shot_events = "\n".join(f"    {event}" for event in self.default_config.one_shot_system_wide_events)

        return "\n".join([
            "[Experiment_Defaults]",
            f"sampling_interval_ms = {self.default_config.sampling_interval_ms}",
            f"action_interval_sec = {self.default_config.action_interval_sec}",
            "",
            "periodic_app_level_events =",
            periodic_app_events,
            "",
            "periodic_system_wide_events =",
            periodic_system_events,
            "",
            "one_shot_system_wide_events =",
            one_shot_events,
            "",
        ])