# Example configuration file for ARDIS.
# Copy this file to `ardis-config.ini` and modify it according to your system setup.
# System: Intel Core i9 12900


[Hardware]
# Number of logical cores in the system
core_count = 24
# Definition of clock domains (sets of cores which share a clock)
# All logical cores must be included in one of the clock domains
clock_domains = 
    [
    {0, 1}, {2, 3}, {4, 5}, {6, 7}, {8, 9}, {10, 11}, {12, 13}, {14, 15}, 
    {16, 17, 18, 19}, {20, 21, 22, 23}
    ]

[Software]
# Temporary directory for ARDIS runtime data
temp_data_dir = /tmp/ardis_runtime_data


[Parsec_Benchmark]
# Flag to enable or disable PARSEC benchmark integration
enabled = false
# Base directory where PARSEC is installed
benchmark_base_dir = </path/to/your/parsec/installation>
# List of available PARSEC packages on this system (uncomment to mark them as available)
available_packages =
    # --- PARSEC benchmarks ---
    parsec.blackscholes
    parsec.bodytrack
    parsec.canneal
    #parsec.facesim
    #parsec.ferret
    parsec.fluidanimate
    #parsec.freqmine
    parsec.dedup
    parsec.streamcluster
    #parsec.swaptions
    #parsec.vips
    #parsec.x264
    # --- PARSEC networked benchmarks ---
    #parsec.netstreamcluster
    #parsec.netdedup
    #parsec.netferret
    # --- SPLASH-2X benchmarks ---
    splash2x.barnes
    #splash2x.cholesky
    splash2x.fft
    #splash2x.fmm
    splash2x.lu_cb
    splash2x.lu_ncb
    splash2x.ocean_cp
    splash2x.ocean_ncp
    splash2x.radiosity
    splash2x.radix
    splash2x.water_nsquared
    splash2x.water_spatial


[Spec2006_Benchmark]
# Flag to enable or disable SPEC CPU 2006 benchmark integration
enabled = false
# Base directoy where SPEC CPU 2006 is installed
benchmark_base_dir = </path/to/your/spec2006/installation>
# Conifg file name of the SPEC config file
config_file = ardis.cfg
# List of available packages on this system (uncomment them to mark them as available)
available_packages =
    GemsFDTD
    #gcc
    milc
    bzip2
    sphinx
    astar
    lbm
    bwaves
    mcf
    zeusmp
    namd
    h264ref
    gobmk
    #libquantum
    povray
    gromacs
    cactusADM
    omnetpp
    hmmer
    leslie3d

[Experiment_Defaults]
action_interval_sec = 0.1
sampling_interval_ms = 100
# Available monitoring backends
# perf: Built-in
# daemon: Requires additionl package (ardis-daemon, currenly not public) 
monitoring_backend = perf

# Perf events to be collected periodically and oneshot during the experiment
# Use `perf list` to see available events on your system.
# Either the event name or an alias can be used.

periodic_app_level_events = 
    instructions
    LLC-loads
    LLC-load-misses
    LLC-stores
    LLC-store-misses
    cycles
    branch-misses
    branch-instructions

periodic_system_wide_events =
    power/energy-pkg/
    power/energy-cores/
    power/energy-psys/

one_shot_system_wide_events =
    power/energy-pkg/
    power/energy-cores/
    power/energy-psys/
    instructions
